// <------------ DOM SELECTORS ------------->
const welcome = document.querySelector("#welcome")
const inputUserName = document.querySelector('#name')
const btn_submit = document.querySelector('#btn-start')
const userName = document.querySelector('.username')
const robotName = document.querySelector('.robot-name')
const wrapContent = document.getElementById('wrap-content')
const gameContentSelector = document.getElementsByName('game-content')
let actionsChoicesSelector = document.querySelectorAll('.user-choice')
const nameFight = document.querySelector('.name-fight')
const ringSVGSelector = document.querySelector('.ring-svg')
const audioPlayer = new Audio('./assets/audio/whoosh.mp3')
// DOM CREATION 
const gameContent = document.createElement('div')
const gameDisplay = document.createElement('div')
const actionsDisplay = document.createElement('div')
const actionsChoices = document.createElement('div')
const roundTitle = document.createElement('h2')
const spanNameFighter = document.createElement('span')
const choicesObj = document.createElement('p')
const resultRound = document.createElement('p')
const handImgOne = document.createElement('img')
const handImgTwo = document.createElement('img')
const rockSVG = document.createElement('img')
const paperSVG = document.createElement('img')
const scissorsSVG = document.createElement('img')
console.log(ringSVGSelector);

//<------------ DOM MODIFICATIONS ------------->
spanNameFighter.classList.add('name-fight')
ringSVGSelector.style.display= "none"
gameContent.setAttribute('id','game-content')
gameDisplay.setAttribute('id','game-display')
gameContent.appendChild(gameDisplay)
roundTitle.classList.add('round-title')
roundTitle.innerHTML="C'est la Bagarre"
roundTitle.appendChild(spanNameFighter)
gameDisplay.appendChild(roundTitle)
choicesObj.classList.add('choices-obj')
choicesObj.innerHTML ='Pierre, Feuille, Ciseaux ?'
resultRound.classList.add('result-round')
gameDisplay.appendChild(choicesObj)
gameDisplay.appendChild( resultRound)
actionsDisplay.setAttribute('id','actions-display')
gameContent.appendChild(actionsDisplay)
handImgOne.setAttribute('src', ' ')
handImgOne.classList.add('handFree')
handImgOne.setAttribute('alt','emoji main ouverte')
handImgTwo.setAttribute('src',' ')
handImgTwo.classList.add('handFree')
handImgTwo.setAttribute('alt','emoji main ouverte')
actionsDisplay.appendChild(handImgOne)
actionsDisplay.appendChild(handImgTwo)
actionsChoices.setAttribute('id','actions-choices')
gameContent.appendChild(actionsChoices)
rockSVG.setAttribute('src', 'assets/svg/rock.svg')
rockSVG.classList.add('user-choice')
rockSVG.setAttribute('alt','icon pierre')
rockSVG.setAttribute('title','Rock')
paperSVG.setAttribute('src', 'assets/svg/paper.svg')
paperSVG.classList.add('user-choice')
paperSVG.setAttribute('alt','icon papier')
paperSVG.setAttribute('title','Paper')
scissorsSVG.setAttribute('src', 'assets/svg/scisors.svg')
scissorsSVG.classList.add('user-choice')
scissorsSVG.setAttribute('alt','icon ciseaux')
scissorsSVG.setAttribute('title','Scissors')
actionsChoices.appendChild(rockSVG)
actionsChoices.appendChild(paperSVG)
actionsChoices.appendChild(scissorsSVG)
handImgOne.src = 'assets/svg/hand_free.svg'
handImgTwo.src = 'assets/svg/hand_free.svg'

