// <------------ DOM SELECTORS ------------->
const welcome = document.querySelector("#welcome")
const inputUserName = document.querySelector('#name')
const btn_submit = document.querySelector('#btn-start')
const userName = document.querySelector('.username')
const robotName = document.querySelector('.robot-name')
const wrapContent = document.getElementById('wrap-content')
const gameContentSelector = document.querySelector("#game-content")
const nameFight = document.querySelector('.name-fight')
const audioPlayer = new Audio('./assets/audio/whoosh.mp3')
// DOM CREATION 
let ringSVG = document.createElement('img')
ringSVG.classList.add('ring-svg')
ringSVG.setAttribute('src','./assets/svg/ring.svg')
let gameContent = document.createElement('div')
let gameDisplay = document.createElement('div')
let actionsDisplay = document.createElement('div')
let actionsChoices = document.createElement('div')
let roundTitle = document.createElement('h2')
let spanNameFighter = document.createElement('span')
let choicesObj = document.createElement('p')
let resultRound = document.createElement('p')
let handImgOne = document.createElement('img')
let handImgTwo = document.createElement('img')
let rockSVG = document.createElement('img')
let paperSVG = document.createElement('img')
let scissorsSVG = document.createElement('img')
console.log(nameFight);

//<------------ DOM MODIFICATIONS ------------->
spanNameFighter.classList.add('name-fight')
gameContent.setAttribute('id','game-content')
gameDisplay.setAttribute('id','game-display')
gameContent.appendChild(gameDisplay)
roundTitle.classList.add('round-title')
roundTitle.innerHTML="C'est la Bagarre"
roundTitle.appendChild(spanNameFighter)
gameDisplay.appendChild(roundTitle)
choicesObj.classList.add('choices-obj')
choicesObj.innerHTML ='Pierre, Feuille, Ciseaux ?'
resultRound.classList.add('result-round')
gameDisplay.appendChild(choicesObj)
gameDisplay.appendChild( resultRound)
actionsDisplay.setAttribute('id','actions-display')
gameContent.appendChild(actionsDisplay)
handImgOne.setAttribute('src', ' ')
handImgOne.classList.add('handFree')
handImgOne.setAttribute('alt','emoji main ouverte')
handImgTwo.setAttribute('src',' ')
handImgTwo.classList.add('handFree')
handImgTwo.setAttribute('alt','emoji main ouverte')
actionsDisplay.appendChild(handImgOne)
actionsDisplay.appendChild(handImgTwo)
actionsChoices.setAttribute('id','actions-choices')
gameContent.appendChild(actionsChoices)
rockSVG.setAttribute('src', 'assets/svg/rock.svg')
rockSVG.classList.add('user-choice')
rockSVG.setAttribute('alt','icon pierre')
rockSVG.setAttribute('title','Rock')
paperSVG.setAttribute('src', 'assets/svg/paper.svg')
paperSVG.classList.add('user-choice')
paperSVG.setAttribute('alt','icon papier')
paperSVG.setAttribute('title','Paper')
scissorsSVG.setAttribute('src', 'assets/svg/scisors.svg')
scissorsSVG.classList.add('user-choice')
scissorsSVG.setAttribute('alt','icon ciseaux')
scissorsSVG.setAttribute('title','Scissors')
actionsChoices.appendChild(rockSVG)
actionsChoices.appendChild(paperSVG)
actionsChoices.appendChild(scissorsSVG)
handImgOne.src = 'assets/svg/hand_free.svg'
handImgTwo.src = 'assets/svg/hand_free.svg'

